README Revisions
imagej/tutorials pull request #93
Opened 2022-01-31 22:17 UTC by jackrueth

This PR updates the main readme of the tutorials repository. 
* Updates the headers for each different way to access the Jupyter Notebooks
* Updated hyperlink to BeakerX
* Updated coloring on the tutorials map

2022-02-03 16:08 UTC, gselzer requested changes
This is a step in the right direction @jackrueth! The new graph looks great on all the Github themes!

2022-02-03 16:08 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
I'm not sure I'd agree that this is the easiest way to view them. I'd actually suggest that the "Using Binder" option below is the easiest. 

What do you think is the best ordering of these options? I'd propose:
1. Using Binder
2. Using Miniconda
3. Viewing the static pages on nbviewer
4. Viewing the static pages on Github

2022-02-03 16:08 UTC, gselzer commented on README.md
>  using [Binder](https://mybinder.org), with no local installation necessary.
I would mention that startup can take a minute.

2022-02-03 16:08 UTC, gselzer commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
Can we add instructions on how to get from the linked page to the notebook pages?

2022-02-03 16:08 UTC, gselzer commented on README.md
> +### Using BeakerX
Can we find a way to separate these informational sections from the viewing instructions? Another header would probably suffice.

2022-02-03 16:39 UTC, ctrueden commented on README.md
> +### (Easiest) Using this Repository
The options are complex and varied enough that perhaps we should have an introductory bullet list, _before_ breaking out into sections. Here is some proposed text:

<blockquote>

There are several ways to work with Jupyter notebooks, each with strengths and weaknesses:

| Method | Pros | Cons | Running live? |
|--------|------|------|---------------|
| Binder | Run code on the cloud, no local installation. | Takes a minute or three to spin up | Yes |
| Local environment | Run code locally on your machine. | Must install developer tools. | Yes |
| On GitHub | View notebooks quickly on GitHub's website. | Code does not run live; rendering is less complete & correct than on nbviewer. | No |
| nbviewer | View notebooks nicely rendered on nbviewer.org. | Code does not run live; not integrated with GitHub. | No |

See the following sections for details on each method.

</blockquote>

2022-02-03 16:41 UTC, ctrueden commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
The link `imagej.github.io/tutorials` needs to be changed to `imagej.github.io/tutorials/notebooks`

2022-02-03 16:46 UTC, ctrueden requested changes
Thanks for working on this, @jackrueth! I added some additional comments beneath @gselzer's comments. 

One additional thing: with ca075cfd952b3d02d632a95d35fbfa5dd8e3127e I don't see any significant different on the lines based on GitHub's image diff view. What changed? It's generally a good practice to provide enough detail in your commit message for people to understand the motivation. A rule of thumb is that a commit message not only explains _what_ you did, but maybe even more importantly _why_ you are doing it.

2022-02-03 16:48 UTC, gselzer commented
> Thanks for working on this, @jackrueth! I added some additional comments beneath @gselzer's comments.
> 
> One additional thing: with [ca075cf](https://github.com/imagej/tutorials/commit/ca075cfd952b3d02d632a95d35fbfa5dd8e3127e) I don't see any significant different on the lines based on GitHub's image diff view. What changed? It's generally a good practice to provide enough detail in your commit message for people to understand the motivation. A rule of thumb is that a commit message not only explains _what_ you did, but maybe even more importantly _why_ you are doing it.

This commit changed the map (image) displayed at the bottom of the `README`. But, I agree, some more elaboration in the commit may have been helpful.

2022-02-03 16:52 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
This is a fantastic suggestion @ctrueden. I'd add in hyperlinks/anchors to the table to make it easy to pick out the option that the user thinks best.

@jackrueth I'm happy to assist you in creating this

2022-02-03 16:53 UTC, gselzer commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
Why do we need that wiki page? It seems like it is just another thing to keep up-to-date. Why can't we just replace all references to that page with this `README`?

2022-02-03 21:05 UTC, ctrueden commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
When you type "jupyter" into the imagej.net search bar, it is the page that comes up first. I think we should keep it, but keep it very trim, linking to the README. I have edited it accordingly.

2022-02-03 21:11 UTC, ctrueden commented
> This commit changed the map (image) displayed at the bottom of the `README`.

Yeah, I know, but I could not tell the difference in the visual diff. I checked out the two versions of the files and compared them locally by eye, and I now see the difference I missed: the commit removes the transparency, filling it instead with white. So it does not actually changes the lines at all—only the background. With a dark theme, I see how the transparent background would be a problem.

Anyway, do we really need that directory diagram? @jackrueth Did you find it helpful? I find it redundant and not really helpful, personally. You can just, you know, look at the directory structure yourself, if you want to see it.

2022-02-03 21:14 UTC, gselzer commented
> Anyway, do we really need that directory diagram? @jackrueth Did you find it helpful? I find it redundant and not really helpful, personally. You can just, you know, look at the directory structure yourself, if you want to see it.

This is a good question. How difficult is it for a novice user to figure out where to learn about the `gauss` Op? If you think that they could do it *easily* without the image, I think we could delete it. But I also don't know why you would delete it, outside of the extra maintenance needs added...

2022-02-03 21:24 UTC, ctrueden commented
> I also don't know why you would delete it, outside of the extra maintenance needs added...

Exactly. Any time something is added or removed, this diagram needs to be updated. It bloats the repository.

> How difficult is it for a novice user to figure out where to learn about the gauss Op?

I don't know. But there are hundreds of ops; are we really going to have them all in a giant image chart?

What's dumb is that if you press <kbd>T</kbd> and type `gauss`, you'll find the gauss notebook. But if you type `gauss` into the search and press enter, you [get this result](https://github.com/imagej/tutorials/search?q=gauss), which does not include that notebook.

2022-02-03 21:31 UTC, gselzer commented
> But I also don't know why you would delete it, outside of the extra maintenance needs added...

Although, the image is actually out-of-date, which makes me lean towards deleting it :laughing:

2022-02-03 21:37 UTC, jackrueth commented on README.md
> +### (Easiest) Using this Repository
I just added this table to commit 539c8fb..b2ac943 . Let me know how it looks!

2022-02-03 21:49 UTC, jackrueth commented on README.md
>  using [Binder](https://mybinder.org), with no local installation necessary.
Added this in commit b2ac943..0c2022d . Thanks!

2022-02-03 21:53 UTC, jackrueth commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
Updated this link in commit 9e6b02d . Link is working well from my end.

2022-02-03 21:59 UTC, jackrueth commented
@ctrueden @gselzer Personally, the diagram was a bit confusing as someone who had no idea how to follow the flow chart. Deleting it may be a good idea to make sure it doesn't distract first time users from more important information.

2022-02-03 22:02 UTC, gselzer commented
> @ctrueden @gselzer Personally, the diagram was a bit confusing as someone who had no idea how to follow the flow chart. Deleting it may be a good idea to make sure it doesn't distract first time users from more important information.

Cool, so long as @elevans is okay with it, can you just remove it from the repo @jackrueth?

2022-02-03 22:07 UTC, jackrueth commented on README.md
> +### Using BeakerX
Consolidated two headers from Using BeakerX and More Information on Jupyter Notebooks into one named Notebook technologies in commit 58aef7a . Let me know how it looks!

2022-02-04 13:06 UTC, elevans commented
No problems here, remove it if it's confusing for folks.

2022-02-04 14:39 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
@jackrueth the table looks great!

Do you think we should make the table option names consistent with the instruction title below?

2022-02-04 14:41 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
And, in that same vein, we should keep the ordering the same between the table and the instruction ordering below

2022-02-04 14:44 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
By the way @jackrueth, it looks like Github does its own markdown cell wrapping. Those `<br>` tags probably aren't necessary, but maybe they still look nice?

2022-02-04 14:45 UTC, gselzer commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
The link looks fine, but I'm confused as to why we are even linking there. It's just going to take us back to this `README` :laughing:

I'd argue we just remove the link.

2022-02-04 14:46 UTC, gselzer commented on README.md
> +### Using BeakerX
This is very nice, thanks. I would maybe suggest using a larger header though, to distinguish this section from the earlier viewing sections.

2022-02-04 19:42 UTC, jackrueth commented on README.md
> +### (Easiest) Using this Repository
1a82bbb commit fixed the titles of the methods to match their corresponding header and fc9e62c fixed the order of the headers to match the order of methods in the table.

2022-02-04 19:47 UTC, jackrueth commented on README.md
>  [ImageJ Jupyter notebooks](https://imagej.github.io/tutorials),
Haha I agree. Just realized that this is unnecessary. Fixed in commit 85c99d9.

2022-02-04 19:50 UTC, jackrueth commented on README.md
> +### Using BeakerX
Agreed. Making it one size better looks better to me so it becomes more noticeable. Commit 443c57c

2022-02-04 19:53 UTC, jackrueth commented
I removed it from the repo and all looks good to me now. Commit b75ebc6.

2022-02-04 19:53 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
Thanks for cleaning this up!

One last gripe: We should have a section on viewing with nbviewer, if it is an option on the table.

I don't remember which link @ctrueden was using, but I'd go with this one:

https://nbviewer.org/github/imagej/tutorials/tree/master/

2022-02-04 19:53 UTC, gselzer commented on README.md
> +### Using BeakerX
Looks great! :1st_place_medal:

2022-02-04 20:07 UTC, jackrueth commented on README.md
> +### (Easiest) Using this Repository
Got it. I added a header and linked it in the table. I also put in a badge that links to the nbviewer. Commit 36c10fd.

2022-02-04 20:12 UTC, gselzer commented on README.md
> +### (Easiest) Using this Repository
Looks great!

2022-02-04 20:12 UTC, gselzer approved these changes

2022-02-10 22:52 UTC, jackrueth commented
@ctrueden @jackrueth need to add section of "Why Jupyter" and edit intro jupyter notebook.

2022-02-11 20:31 UTC, jackrueth commented
@ctrueden I created a header that we discussed yesterday called Why Jupyter to the README under commit 4447da7 . Wondering what you think a good description for this section would be? I added a little that I thought worked but am looking for your input.

2022-02-17 21:57 UTC, ctrueden commented
Action items from our meeting today:

* Flesh out "Why Jupyter" blurb: "[Jupyter notebooks](https://jupyter.org/) are a great outreach tool to demonstrate how programs work interactively in real time. We use Jupyter for teaching ImageJ2 so that you can try and change the code yourself easily. See the [Why Jupyter? notebook](notebooks/0-Why-Jupyter.ipynb) if you have never used Jupyter notebook before."

* Slim down the toplevel README in favor of the notebooks and java sub-READMEs.
    * Make the toplevel README explain that both exist, and link to both.
    * Notebooks are a “guided tour” teaching ImageJ2.
    * Java code is a collection of examples and howtos for different use cases.
    * Take out the flow charts

See [the meeting Google Doc]([Jupyter notebooks](https://jupyter.org/) are a great outreach tool to demonstrate how programs work interactively in real time. We use Jupyter for teaching ImageJ2 so that you can try and change the code yourself easily. See the [Why Jupyter? notebook](notebooks/0-Why-Jupyter.ipynb) if you have never used Jupyter notebook before.) for full notes.

2022-03-21 20:25 UTC, merged

2022-03-21 20:25 UTC, ctrueden commented
Whoo hoo, thanks @jackrueth!