Add Java-like Comments to Groovy Kernel
imagej/tutorials pull request #95
Opened 2022-03-24 21:53 UTC by jackrueth

This branch consists of comments added to the tutorials notebooks with Java syntax in places where Groovy syntax was confusing.

2022-03-24 21:59 UTC, ctrueden requested changes

2022-03-24 21:59 UTC, ctrueden commented on notebooks/1-Using-ImageJ/1-Fundamentals.ipynb
> -    "// Create an ImageJ gateway.\n",
I would prefer not to delete the term "gateway" here. This term is used everywhere, and explicitly explained in the notebooks. If you found the term "gateway" confusing, then we didn't do a good enough job introducing it.

2022-03-24 21:59 UTC, ctrueden commented on notebooks/1-Using-ImageJ/1-Fundamentals.ipynb
> +    "// In Groovy, [] creates a list or map\n",
The actual thing created in this case will be an `ArrayList`. For maps, Groovy uses `LinkedHashMap` to preserve order. Don't know if it's worth mentioning, but Java people might feel more comfortable being told that?

2022-03-24 21:59 UTC, ctrueden commented on notebooks/1-Using-ImageJ/3-ImgLib2-Basics.ipynb
> +    "// Groovy uses \"in\" where java would use \":\"\n",
The technical term for this kind of for loop is "foreach loop". Maybe we should say that too? `Groovy foreach loops use 'in' where java would use ':'` ?

2022-03-24 21:59 UTC, ctrueden commented on notebooks/ImageJ-Tutorials-and-Demo.ipynb
> +    "// Creates a new ImageJ class variable ij\n",
Again, the technical term is "ImageJ gateway": the entry point into ImageJ. Yes, it is a class variable, and that's OK to say in the section where we talk about what a gateway is. Now that I'm typing this: I guess we explain what a gateway is in the 1-1 notebook, not the Tutorials-and-Demo? In which case, a one-sentence statement like "Creates a new ImageJ2 gateway, a variable serving as the central entry point into ImageJ2 functionality." could be used?

2022-03-25 18:48 UTC, jackrueth commented on notebooks/1-Using-ImageJ/1-Fundamentals.ipynb
> -    "// Create an ImageJ gateway.\n",
I added "gateway" back and also changed it to ImageJ2 gateway. The only reason I removed it is because I did not know if it was correct but now I understand after looking at it again.

2022-03-25 18:49 UTC, jackrueth commented on notebooks/1-Using-ImageJ/1-Fundamentals.ipynb
> +    "// In Groovy, [] creates a list or map\n",
I switched up the wording according to this. Thanks for the help here.

2022-03-26 02:37 UTC, merged

2022-03-26 02:37 UTC, ctrueden commented
Thanks @jackrueth!